### PR TITLE
Add --manylinux=[1|1-unchecked|off] to fix #51

### LINKED ISSUE #51: Support non-manylinux Linux builds
Linux builds should be able to target their specific installation rather than the manylinux1 target. Maybe a flag of `--env-specific` or something better named, which implies `--skip-auditwheel`, and generates the `...-cp37-cp37m-linux_x86_64.whl` tag?

### PR DESCRIPTION
**Pull request by konstin**

### CODE REVIEW

**Comment by ijl** [comment]
I tried this locally and see it working well for #51.

**Comment by discosultan** [comment]
Thanks for the change! What is the plan/status of releasing a new version of `pyo3-pack`?

**Comment by konstin** [comment]
I want to make a release rather soon, but I'd like to merge #52 first (which is mainly blocked on me fixing windows CI).

**Comment by discosultan** [comment]
@konstin Cool, thanks for the update!

**Comment by konstin** [comment]
@discosultan I've published 0.5.0-alpha.1 with you're eager to try things out. The artifacts should show up in github releases, pypi and docker hub soon.

**Pull request merged**
